// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE3j7Rt4loAGed7ET1jLDvUfoI-MGnSZY',
    appId: '1:964683754957:web:1d21f5eb85ee49c0042884',
    messagingSenderId: '964683754957',
    projectId: 'petsycare-10533',
    authDomain: 'petsycare-10533.firebaseapp.com',
    storageBucket: 'petsycare-10533.firebasestorage.app',
    measurementId: 'G-W3FN13R23Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHf19K5grxX58sEgzXSQq-zTZXgrpP-k4',
    appId: '1:964683754957:android:4365456e522ea20c042884',
    messagingSenderId: '964683754957',
    projectId: 'petsycare-10533',
    storageBucket: 'petsycare-10533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr3Zym9hvRS6pRq9dnfW6AnvOxhV4JAlI',
    appId: '1:964683754957:ios:86cd781f660d509f042884',
    messagingSenderId: '964683754957',
    projectId: 'petsycare-10533',
    storageBucket: 'petsycare-10533.firebasestorage.app',
    iosBundleId: 'com.example.petsyCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr3Zym9hvRS6pRq9dnfW6AnvOxhV4JAlI',
    appId: '1:964683754957:ios:86cd781f660d509f042884',
    messagingSenderId: '964683754957',
    projectId: 'petsycare-10533',
    storageBucket: 'petsycare-10533.firebasestorage.app',
    iosBundleId: 'com.example.petsyCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE3j7Rt4loAGed7ET1jLDvUfoI-MGnSZY',
    appId: '1:964683754957:web:65c2650f3e82f388042884',
    messagingSenderId: '964683754957',
    projectId: 'petsycare-10533',
    authDomain: 'petsycare-10533.firebaseapp.com',
    storageBucket: 'petsycare-10533.firebasestorage.app',
    measurementId: 'G-RQZ5KTJGZF',
  );
}
